backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "教学文章"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "标题"
        name: "title"
        widget: "string"
      - label: "日期"
        name: "date"
        widget: "datetime"
      - label: "简介"
        name: "description"
        widget: "text"
      - label: "正文"
        name: "body"
        widget: "markdown"